kind: pipeline
type: vm
name: testing

pool:
  use: ubuntu

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: golang:1.16
    commands:
      - go test -cover ./...
    volumes:
      - name: go
        path: /go

  - name: build
    image: golang:1.16
    commands:
      - sh scripts/build.sh
    volumes:
      - name: go
        path: /go

volumes:
  - name: go
    temp: {}

---

kind: pipeline
type: vm
name: linux-amd64
platform:
  os: linux
  arch: amd64
pool:
  use: ubuntu

steps:
  - name: environment
    image: golang:1.16
    pull: always
    environment:
      CGO_ENABLED: "0"
    commands:
      - go version
      - go env
  - name: build
    image: golang:1.16
    environment:
      CGO_ENABLED: "0"
    commands:
      - go build -o release/linux/amd64/drone-runner-docker
  - name: publish
    image: plugins/docker
    pull: if-not-exists
    settings:
      repo: drone/drone-runner-docker
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: docker/Dockerfile.linux.amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      ref:
        - refs/heads/master
        - refs/tags/*

depends_on:
  - testing

trigger:
  ref:
    - refs/heads/master
    - refs/tags/**
    - refs/pull/**

---


kind: pipeline
type: vm
name: linux-arm64
platform:
  os: linux
  arch: arm64
pool:
  use: ubuntu_arm64

steps:
  - name: environment
    image: golang:1.16
    pull: always
    environment:
      CGO_ENABLED: "0"
    commands:
      - go version
      - go env
  - name: build
    image: golang:1.16
    environment:
      CGO_ENABLED: "0"
    commands:
      - go build -o release/linux/arm64/drone-runner-docker
  - name: publish
    image: plugins/docker
    pull: if-not-exists
    settings:
      repo: drone/drone-runner-docker
      auto_tag: true
      auto_tag_suffix: linux-arm64
      dockerfile: docker/Dockerfile.linux.arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      ref:
        - refs/heads/master
        - refs/tags/*

depends_on:
  - testing

trigger:
  ref:
    - refs/heads/master
    - refs/tags/**
    - refs/pull/**

---
kind: pipeline
type: vm
name: windows-1809

platform:
  os: windows
  arch: amd64

pool:
  use: windows

steps:
  - name: environment
    image: golang:1.16
    pull: always
    environment:
      CGO_ENABLED: "0"
    commands:
      - go version
      - go env
  - name: build
    image: golang:1.16
    environment:
      CGO_ENABLED: "0"
    commands:
      - go build -o release/windows/amd64/drone-runner-docker.exe
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile.windows.1809
      repo: drone/drone-runner-docker
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: windows-1809-amd64
      daemon_off: true
      purge: false
    when:
      ref:
        - refs/heads/master
        - refs/tags/**

depends_on:
  - testing

trigger:
  ref:
    - refs/heads/master
    - refs/tags/**
    - refs/pull/**

---
kind: pipeline
type: vm
name: windows-ltsc2022

platform:
  os: windows
  arch: amd64

pool:
  use: windows-2022

steps:
  - name: environment
    image: golang:1.16
    pull: always
    environment:
      CGO_ENABLED: "0"
    commands:
      - go version
      - go env
  - name: build
    image: golang:1.16
    environment:
      CGO_ENABLED: "0"
    commands:
      - go build -o release/windows/amd64/drone-runner-docker.exe
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile.windows.ltsc2022
      repo: drone/drone-runner-docker
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: windows-ltsc2022-amd64
      daemon_off: true
      purge: false
    when:
      ref:
        - refs/heads/master
        - refs/tags/**

depends_on:
  - testing
  
trigger:
  ref:
    - refs/heads/master
    - refs/tags/**
    - refs/pull/**

---

kind: pipeline
type: docker
name: manifest

steps:
  - name: manifest
    image: plugins/manifest
    settings:
      spec: docker/manifest.tmpl
      auto_tag: true
      ignore_missing: true
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username

depends_on:
  - linux-amd64
  - linux-arm64
  - windows-1809
  - windows-ltsc2022

trigger:
  ref:
    - refs/heads/master
    - refs/tags/*
